name: E2ETests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  E2ETests:
    name: 'Build & Test'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install
        run: npm ci --ignore-scripts

      - name: Check Lint
        run: npx eslint src

      - name: Check Build
        run: npm run build

      - name: Test Public API Calls
        run: npm run test -- public.test.ts

      - name: Test Private API Calls
        run: npm run test -- private.test.ts
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          API_PASSPHRASE: ${{ secrets.API_PASSPHRASE }}
          PROXY_ENABLED: ${{ secrets.PROXY_ENABLED }}
          PROXY_HOST: ${{ secrets.PROXY_HOST }}
          PROXY_PASS: ${{ secrets.PROXY_PASS }}
          PROXY_PORT: ${{ secrets.PROXY_PORT }}
          PROXY_USER: ${{ secrets.PROXY_USER }}
